"""U7 tests: intensity routing, breaker, generations, surprises (plan Phase B).

Sessions are scripted in-process: StubRunner plays canned final messages per
session, so every scenario (approve, reject-then-approve, reject-forever,
surprise, too-hard) runs with zero subprocesses and zero tokens.
"""

from __future__ import annotations

import json
import re
from pathlib import Path

import pytest

from orchestrator.config import BreakerConfig, ExecutionConfig
from orchestrator.execution.escalation import EscalationPolicy
from orchestrator.execution.manifest import ManifestStore, RunPaths
from orchestrator.execution.review import (
    GroupFailure,
    MergeConflict,
    ReviewDeps,
    SurpriseBoard,
    make_executor,
)
from orchestrator.execution.scheduler import GroupContext, GroupState, RunAbort
from orchestrator.execution.sessions import (
    RoundResult,
    RoundUsage,
    SessionError,
    SessionUsage,
    UsageLimit,
)
from orchestrator.execution.streaming import TurnUsage
from orchestrator.model import (
    EscalationKind,
    EscalationRequest,
    EscalationResponse,
    Group,
    GroupManifestEntry,
    HumanAction,
    PermissionDenied,
    ReviewIntensity,
    RunManifest,
    SessionEntry,
    SessionRole,
    Surprise,
    VerificationItem,
)


def coder_report(
    status: str = "completed",
    surprises: list[dict] | None = None,
    question: str = "",
    denied_command: str = "",
    denial_error: str = "",
    denial_source: str = "",
) -> str:
    body: dict = {
        "status": status,
        "summary": "round done",
        "verification_results": [{"item_id": "v1", "status": "pass", "notes": ""}],
        "surprises": surprises or [],
    }
    if question:
        body["question"] = question
    if denied_command:
        body["denied_command"] = denied_command
    if denial_error:
        body["denial_error"] = denial_error
    if denial_source:
        body["denial_source"] = denial_source
    return f'<run-report status="{status}">\n{json.dumps(body)}\n</run-report>'


def verdict(
    status: str = "approved", changes: list[str] | None = None, surprises: list[dict] | None = None
) -> str:
    body = {
        "status": status,
        "required_changes": changes or [],
        "surprises": surprises or [],
        "notes": "",
    }
    return f'<run-report status="{status}">\n{json.dumps(body)}\n</run-report>'


class StubRunner:
    """Scripted sessions: fork scripts are keyed by display name; the queue then
    serves that session's resumes in order."""

    def __init__(self, fork_scripts: dict[str, list[str]]):
        self.fork_scripts = {name: list(queue) for name, queue in fork_scripts.items()}
        self.session_queues: dict[str, list[str]] = {}
        self.context_tokens: dict[str, int] = {}
        self.forks: list[str] = []
        self.prompts: dict[str, list[str]] = {}
        # name -> the session id actually assigned to that fork (plan U7: the
        # coder's id is now generated by the caller before the call, not by
        # this stub, so tests look it up by fork name instead of assuming a
        # fixed "sess-N" sequence).
        self.session_ids: dict[str, str] = {}
        self.on_fork = None  # optional hook(name) — lets tests interleave events
        self._counter = 0
        self.model = "stub-model"
        # session_id -> queue of per-call turn-usage lists (plan U1/U3/U4): one
        # list is consumed per start_fork/resume call that names that session,
        # fed to on_turn synchronously before the canned final result returns.
        self.turn_sequences: dict[str, list[list[TurnUsage]]] = {}
        # session_id -> every string handed to on_turn's `send` across every
        # call, in order — what a context-ladder prompt actually looked like.
        self.sent: dict[str, list[str]] = {}
        self.disallowed: list[str] = []

    def start_fork(
        self, *, base_id, prompt, name, cwd, session_id=None, json_schema=None, on_turn=None
    ) -> RoundResult:
        self._counter += 1
        session_id = session_id or f"sess-{self._counter}"
        self.forks.append(name)
        self.session_ids[name] = session_id
        self.session_queues[session_id] = self.fork_scripts[name]
        self.prompts[session_id] = [prompt]
        if self.on_fork is not None:
            self.on_fork(name)
        self._play_turns(session_id, on_turn)
        return self._round(session_id)

    def resume(self, *, session_id, prompt, cwd, json_schema=None, on_turn=None) -> RoundResult:
        self.prompts[session_id].append(prompt)
        self._play_turns(session_id, on_turn)
        return self._round(session_id)

    def effective_disallowed_tools(self) -> list[str]:
        # The real runner composes deny rules from config plus its built-in safety
        # set; the classifier reads them to attribute POLICY_FORBIDDEN. Tests that
        # care set `disallowed` on the instance.
        return list(self.disallowed)

    def usage_of(self, session_id: str) -> SessionUsage:
        return SessionUsage(last_context_tokens=self.context_tokens.get(session_id, 1_000))

    def transcript_path(self, session_id: str) -> Path | None:
        return None

    def _play_turns(self, session_id: str, on_turn) -> None:
        if on_turn is None:
            return
        queue = self.turn_sequences.get(session_id)
        if not queue:
            return
        turns = queue.pop(0)

        def send(text: str) -> None:
            self.sent.setdefault(session_id, []).append(text)

        for turn in turns:
            on_turn(turn, send)

    def _round(self, session_id: str) -> RoundResult:
        text = self.session_queues[session_id].pop(0)
        return RoundResult(session_id=session_id, text=text, usage=RoundUsage(), envelope={})


def make_group(gid: str = "g1", intensity=ReviewIntensity.PAIRED, **overrides) -> Group:
    defaults = dict(
        id=gid,
        name=f"group {gid}",
        summary=f"summary {gid}",
        spec=f"spec {gid} v1",
        difficulty=0.5,
        intensity=intensity,
        verification=[VerificationItem(id="v1", description="tests pass")],
    )
    defaults.update(overrides)
    return Group(**defaults)


class StubBroker:
    """Canned operator: returns a scripted response keyed by escalation kind, or
    None (→ autonomous fallback). Records every request it was asked to raise."""

    def __init__(self, responses: dict[EscalationKind, EscalationResponse | None] | None = None):
        self.responses = responses or {}
        self.raised: list[EscalationRequest] = []
        self.aborted = False

    def raise_escalation(self, request: EscalationRequest) -> EscalationResponse | None:
        self.raised.append(request)
        return self.responses.get(request.kind)

    def trigger_abort(self) -> None:
        self.aborted = True


def answer(text: str = "") -> EscalationResponse:
    return EscalationResponse(id="x", action=HumanAction.ANSWER, answer=text)


def skip() -> EscalationResponse:
    return EscalationResponse(id="x", action=HumanAction.SKIP)


def abort() -> EscalationResponse:
    return EscalationResponse(id="x", action=HumanAction.ABORT)


class Harness:
    """Deps + context wiring shared by every scenario."""

    def __init__(
        self,
        tmp_path: Path,
        runner: StubRunner,
        *,
        breaker=None,
        execution=None,
        broker: StubBroker | None = None,
        policy: EscalationPolicy | None = None,
    ):
        self.runner = runner
        self.store = ManifestStore(RunPaths(tmp_path, "r1"))
        self.manifest = RunManifest(run_id="r1", plan_path="p.md", base_session_id="base-0")
        self.board = SurpriseBoard()
        self.merged: list[str] = []
        self.rewritten: list[list[Surprise]] = []
        self.merge_failures: list[MergeConflict] = list()
        self.states: list[GroupState] = []
        self.generations: list[int] = []
        self.workspace = tmp_path / "ws"
        self.workspace.mkdir(exist_ok=True)

        def merge_group(group: Group, workspace: Path) -> None:
            if self.merge_failures:
                raise self.merge_failures.pop(0)
            self.merged.append(group.id)

        def rewrite_spec(group: Group, surprises: list[Surprise]) -> Group:
            self.rewritten.append(surprises)
            return group.model_copy(update={"spec": group.spec.replace("v1", "v2")})

        self.deps = ReviewDeps(
            run_id="r1",
            runner=runner,
            store=self.store,
            manifest=self.manifest,
            base_session_id="base-0",
            breaker=breaker or BreakerConfig(),
            execution=execution or ExecutionConfig(),
            board=self.board,
            workspace_for=lambda group: self.workspace,
            merge_group=merge_group,
            rewrite_spec=rewrite_spec,
            base_ref_for=lambda group: "main",
            broker=broker,
            policy=policy,
        )

    def context(self, group: Group) -> GroupContext:
        return GroupContext(
            group=group,
            generation=1,
            set_state=self.states.append,
            set_generation=self.generations.append,
        )

    async def run(self, group: Group) -> GroupState:
        return await make_executor(self.deps)(self.context(group))


@pytest.mark.asyncio
async def test_self_verify_group_never_creates_a_reviewer_session(tmp_path):
    # AE7: below d_review — coder self-verifies, straight to merge.
    runner = StubRunner({"r1-g1-coder-g1": [coder_report()]})
    harness = Harness(tmp_path, runner)
    state = await harness.run(make_group(intensity=ReviewIntensity.SELF_VERIFY))
    assert state == GroupState.COMPLETED
    assert runner.forks == ["r1-g1-coder-g1"]
    assert harness.merged == ["g1"]
    roles = [s.role.value for s in harness.manifest.groups["g1"].sessions]
    assert roles == ["coder"]


@pytest.mark.asyncio
async def test_paired_approval_merges_and_persists_report_and_verdict(tmp_path):
    runner = StubRunner(
        {"r1-g1-coder-g1": [coder_report()], "r1-g1-reviewer-g1": [verdict("approved")]}
    )
    harness = Harness(tmp_path, runner)
    state = await harness.run(make_group())
    assert state == GroupState.COMPLETED
    group_dir = harness.store.paths.group_dir("g1")
    assert (group_dir / "report-g1-r1.json").is_file()
    assert (group_dir / "verdict-g1-r1.json").is_file()
    # reviewer got a pointer to the report, not the report body
    reviewer_first_prompt = runner.prompts[runner.session_ids["r1-g1-reviewer-g1"]][0]
    assert str(group_dir / "report-g1-r1.json") in reviewer_first_prompt
    assert "round done" not in reviewer_first_prompt


@pytest.mark.asyncio
async def test_changes_required_under_thresholds_resumes_same_session(tmp_path):
    # AE3: warm continuation — no new manifest entry, same coder session.
    runner = StubRunner(
        {
            "r1-g1-coder-g1": [coder_report(), coder_report()],
            "r1-g1-reviewer-g1": [verdict("changes_required", ["fix x"]), verdict("approved")],
        }
    )
    harness = Harness(tmp_path, runner)
    state = await harness.run(make_group())
    assert state == GroupState.COMPLETED
    sessions = harness.manifest.groups["g1"].sessions
    assert [s.name for s in sessions] == ["r1-g1-coder-g1", "r1-g1-reviewer-g1"]
    assert all(s.retirement_reason is None for s in sessions)
    revision_prompt = runner.prompts[runner.session_ids["r1-g1-coder-g1"]][1]
    assert "fix x" in revision_prompt and "verdict-g1-r1.json" in revision_prompt


@pytest.mark.asyncio
async def test_round_threshold_trips_breaker_into_generation_two(tmp_path):
    # AE4: gen-1 retired with a reason; gen-2 forked fresh from base with a handoff.
    runner = StubRunner(
        {
            "r1-g1-coder-g1": [coder_report()],
            "r1-g1-reviewer-g1": [verdict("changes_required", ["fix y"])],
            "r1-g1-coder-g2": [coder_report()],
            "r1-g1-reviewer-g2": [verdict("approved")],
        }
    )
    harness = Harness(
        tmp_path, runner, breaker=BreakerConfig(max_rounds_per_generation=1, max_generations=3)
    )
    state = await harness.run(make_group())
    assert state == GroupState.COMPLETED
    sessions = harness.manifest.groups["g1"].sessions
    coder_g1 = next(s for s in sessions if s.name == "r1-g1-coder-g1")
    assert (
        coder_g1.retirement_reason is not None and "round threshold" in coder_g1.retirement_reason
    )
    assert any(s.name == "r1-g1-coder-g2" and s.generation == 2 for s in sessions)
    handoff = runner.prompts[runner.session_ids["r1-g1-coder-g2"]][0]  # gen-2 coder's first prompt
    assert "generation 2" in handoff and "fix y" in handoff
    assert harness.generations == [2]


@pytest.mark.asyncio
async def test_token_threshold_trips_independently_of_round_count(tmp_path):
    runner = StubRunner(
        {
            "r1-g1-coder-g1": [coder_report()],
            "r1-g1-reviewer-g1": [verdict("changes_required", ["fix z"])],
            "r1-g1-coder-g2": [coder_report()],
            "r1-g1-reviewer-g2": [verdict("approved")],
        }
    )
    harness = Harness(
        tmp_path,
        runner,
        breaker=BreakerConfig(
            max_rounds_per_generation=10, max_generations=3, context_token_limit=150_000
        ),
    )

    def seed_context_tokens(name: str) -> None:
        # over the limit after round 1 — session id isn't known until the fork
        # actually runs, so this hooks the fork instead of pre-seeding a fixed id.
        if name == "r1-g1-coder-g1":
            runner.context_tokens[runner.session_ids[name]] = 200_000

    runner.on_fork = seed_context_tokens
    state = await harness.run(make_group())
    assert state == GroupState.COMPLETED
    coder_g1 = harness.manifest.groups["g1"].sessions[0]
    assert coder_g1.retirement_reason is not None and "context tokens" in coder_g1.retirement_reason


@pytest.mark.asyncio
async def test_generation_cap_fails_the_group_instead_of_respawning(tmp_path):
    runner = StubRunner(
        {
            "r1-g1-coder-g1": [coder_report()],
            "r1-g1-reviewer-g1": [verdict("changes_required", ["never good enough"])],
        }
    )
    harness = Harness(
        tmp_path, runner, breaker=BreakerConfig(max_rounds_per_generation=1, max_generations=1)
    )
    with pytest.raises(GroupFailure, match="generation cap"):
        await harness.run(make_group())
    # the retirement reason still lands in the manifest for the operator
    assert harness.manifest.groups["g1"].sessions[0].retirement_reason is not None


@pytest.mark.asyncio
async def test_too_hard_moves_group_to_rewriting_not_another_round(tmp_path):
    runner = StubRunner(
        {
            "r1-g1-coder-g1": [coder_report()],
            "r1-g1-reviewer-g1": [verdict("too_hard")],
            "r1-g1-coder-g2": [coder_report()],
            "r1-g1-reviewer-g2": [verdict("approved")],
        }
    )
    harness = Harness(tmp_path, runner)
    state = await harness.run(make_group())
    assert state == GroupState.COMPLETED
    assert GroupState.REWRITING in harness.states
    assert len(harness.rewritten) == 1
    # the respawned coder got the rewritten spec, not a handoff
    assert "spec g1 v2" in runner.prompts[runner.session_ids["r1-g1-coder-g2"]][0]


@pytest.mark.asyncio
async def test_surprise_during_review_blocks_pending_approval(tmp_path):
    # A group already in review when a surprise names it moves to rewriting
    # instead of merging — even though its reviewer said approved.
    runner = StubRunner(
        {
            "r1-g1-coder-g1": [coder_report()],
            "r1-g1-reviewer-g1": [verdict("approved")],
            "r1-g1-coder-g2": [coder_report()],
            "r1-g1-reviewer-g2": [verdict("approved")],
        }
    )
    harness = Harness(tmp_path, runner)
    surprise = Surprise(
        kind="interface_mismatch", description="g3 changed the API", affected_groups=["g1"]
    )

    def mark_during_review(name: str) -> None:
        if "reviewer-g1" in name:
            harness.board.mark(surprise, source_group="g3")

    runner.on_fork = mark_during_review
    state = await harness.run(make_group())
    assert state == GroupState.COMPLETED
    assert GroupState.REWRITING in harness.states
    assert harness.rewritten == [[surprise]]
    assert harness.merged == ["g1"]  # merged only after the rewrite cycle


@pytest.mark.asyncio
async def test_upstream_surprise_rewrites_dependent_before_launch(tmp_path):
    # AE5 (rewrite half): the mark is consumed before any session is forked.
    runner = StubRunner(
        {"r1-g2-coder-g1": [coder_report()], "r1-g2-reviewer-g1": [verdict("approved")]}
    )
    harness = Harness(tmp_path, runner)
    surprise = Surprise(
        kind="missing_dependency", description="g1 renamed the helper", affected_groups=["g2"]
    )
    harness.board.mark(surprise, source_group="g1")
    state = await harness.run(make_group("g2"))
    assert state == GroupState.COMPLETED
    assert harness.rewritten == [[surprise]]
    assert runner.forks[0] == "r1-g2-coder-g1"  # still generation 1
    assert "spec g2 v2" in runner.prompts[runner.session_ids["r1-g2-coder-g1"]][0]


@pytest.mark.asyncio
async def test_coder_surprises_fan_out_to_other_groups_but_not_itself(tmp_path):
    runner = StubRunner(
        {
            "r1-g1-coder-g1": [
                coder_report(
                    surprises=[
                        {
                            "kind": "interface_mismatch",
                            "description": "changed shared enum",
                            "affected_groups": ["g1", "g2", "g3"],
                        }
                    ]
                )
            ],
            "r1-g1-reviewer-g1": [verdict("approved")],
        }
    )
    harness = Harness(tmp_path, runner)
    state = await harness.run(make_group())
    assert state == GroupState.COMPLETED  # its own surprise must not self-rewrite
    assert harness.board.pending_for("g2") and harness.board.pending_for("g3")
    assert not harness.board.pending_for("g1")


@pytest.mark.asyncio
async def test_paired_plus_runs_one_mandatory_extra_verification_pass(tmp_path):
    runner = StubRunner(
        {
            "r1-g1-coder-g1": [coder_report()],
            "r1-g1-reviewer-g1": [verdict("approved"), verdict("approved")],
        }
    )
    harness = Harness(tmp_path, runner)
    state = await harness.run(make_group(intensity=ReviewIntensity.PAIRED_PLUS))
    assert state == GroupState.COMPLETED
    reviewer_prompts = runner.prompts["sess-2"]
    assert len(reviewer_prompts) == 2 and "extra verification pass" in reviewer_prompts[1].lower()
    assert (harness.store.paths.group_dir("g1") / "verdict-g1-r1-extra.json").is_file()


@pytest.mark.asyncio
async def test_merge_conflict_resolves_in_place_on_the_warm_coder_session(tmp_path):
    # U1: the first conflict resumes the same coder session (not a fresh fork)
    # and the resolve attempt clears it — no rewrite needed at all.
    runner = StubRunner(
        {
            "r1-g1-coder-g1": [coder_report(), coder_report()],
            "r1-g1-reviewer-g1": [verdict("approved")],
        }
    )
    harness = Harness(tmp_path, runner)
    harness.merge_failures.append(MergeConflict("g1 conflicts with g0", ["g0", "g2"]))
    state = await harness.run(make_group())
    assert state == GroupState.COMPLETED
    assert GroupState.MERGING in harness.states
    assert GroupState.REWRITING not in harness.states  # resolved in place, no rewrite spent
    assert harness.merged == ["g1"]
    assert not harness.rewritten
    assert harness.board.pending_for("g2")  # conflict surprise still reached others
    coder_sid = runner.session_ids["r1-g1-coder-g1"]
    prompts = runner.prompts[coder_sid]
    assert len(prompts) == 2  # same warm session: initial prompt + the resolve prompt
    assert "conflict" in prompts[1].lower()


@pytest.mark.asyncio
async def test_merge_conflict_routes_to_rewriting_and_fans_out_a_surprise(tmp_path):
    # The resolve attempt itself clears cleanly, but the merge conflicts again on
    # retry — the single resolve attempt (default cap 1) is exhausted, so the
    # group falls through to the proven rewrite path exactly as before U1.
    runner = StubRunner(
        {
            "r1-g1-coder-g1": [coder_report(), coder_report()],
            "r1-g1-reviewer-g1": [verdict("approved")],
            "r1-g1-coder-g2": [coder_report()],
            "r1-g1-reviewer-g2": [verdict("approved")],
        }
    )
    harness = Harness(tmp_path, runner)
    harness.merge_failures.append(MergeConflict("g1 conflicts with g0", ["g0", "g2"]))
    harness.merge_failures.append(MergeConflict("g1 conflicts with g0 again", ["g0", "g2"]))
    state = await harness.run(make_group())
    assert state == GroupState.COMPLETED
    assert GroupState.MERGING in harness.states and GroupState.REWRITING in harness.states
    assert harness.merged == ["g1"]
    assert len(harness.rewritten) == 1  # resolve attempt exhausted, then one rewrite
    assert harness.board.pending_for("g2")  # conflict surprise reached others
    # the resolve attempt itself resumed the pre-conflict coder session, not a
    # fresh fork — confirmed by the fork list only ever containing generation 2
    # once the rewrite actually happens.
    assert runner.forks == [
        "r1-g1-coder-g1",
        "r1-g1-reviewer-g1",
        "r1-g1-coder-g2",
        "r1-g1-reviewer-g2",
    ]


@pytest.mark.asyncio
async def test_rewrite_cap_fails_the_group(tmp_path):
    runner = StubRunner(
        {
            "r1-g1-coder-g1": [coder_report()],
            "r1-g1-reviewer-g1": [verdict("too_hard")],
            "r1-g1-coder-g2": [coder_report()],
            "r1-g1-reviewer-g2": [verdict("too_hard")],
        }
    )
    harness = Harness(tmp_path, runner, execution=ExecutionConfig(max_rewrites=1))
    with pytest.raises(GroupFailure, match="rewrite cap"):
        await harness.run(make_group())


@pytest.mark.asyncio
async def test_blocked_coder_report_escalates_to_rewriting(tmp_path):
    runner = StubRunner(
        {
            "r1-g1-coder-g1": [coder_report("blocked")],
            "r1-g1-coder-g2": [coder_report()],
            "r1-g1-reviewer-g2": [verdict("approved")],
        }
    )
    harness = Harness(tmp_path, runner)
    state = await harness.run(make_group())
    assert state == GroupState.COMPLETED
    assert len(harness.rewritten) == 1


# ------------------------------------------------------------ U3: typed denial


@pytest.mark.asyncio
async def test_permission_denied_raises_and_costs_no_rewrite(tmp_path):
    # Plan U3: bypasses _on_coder_stuck/_rewrite entirely — no escalation, no
    # rewrite, the denied command survives verbatim on the raised exception so
    # the scheduler can record it in the group's failure text.
    runner = StubRunner(
        {"r1-g1-coder-g1": [coder_report("permission_denied", denied_command="rm -rf /etc")]}
    )
    harness = Harness(tmp_path, runner)
    with pytest.raises(PermissionDenied, match=re.escape("rm -rf /etc")):
        await harness.run(make_group())
    assert harness.rewritten == []  # same rewrite count as a group that never reported


@pytest.mark.asyncio
async def test_a_denial_carries_its_attributed_kind_all_the_way_out(tmp_path):
    """P2: three causes, one status — so the *kind* has to reach the operator.

    It rides in `str(exc)` deliberately, not only on the instance: the scheduler
    already writes `f"{type(exc).__name__}: {exc}"` into `state.json`, which
    `status` prints and the Observatory reads, so this is the whole path from a
    worker's report to a UI with no schema change on the way.
    """
    runner = StubRunner(
        {
            "r1-g1-coder-g1": [
                coder_report(
                    "permission_denied",
                    denied_command="uv run pytest",
                    denial_error=(
                        "Failed to initialize cache at /home/op/.cache/uv: "
                        "Permission denied (os error 13)"
                    ),
                    denial_source="command_error",
                )
            ]
        }
    )
    harness = Harness(tmp_path, runner)
    with pytest.raises(PermissionDenied) as caught:
        await harness.run(make_group())

    assert caught.value.kind == "kernel_denied"
    assert "kernel_denied" in str(caught.value)
    assert caught.value.denied_command == "uv run pytest"

    lines = run_log_lines(harness)
    assert any(line.endswith("round 1: ended (permission_denied: kernel_denied)") for line in lines)
    # And the remedy, because a kind without one tells an operator nothing.
    assert any("the kernel refused a write" in line for line in lines)


@pytest.mark.asyncio
async def test_a_forbidden_command_is_attributed_from_the_runners_own_deny_rules(tmp_path):
    """The rule that needs nothing from the report: the orchestrator knows its own
    deny list, so this attribution holds even for a coder that quoted nothing."""
    runner = StubRunner(
        {"r1-g1-coder-g1": [coder_report("permission_denied", denied_command="git stash pop")]}
    )
    runner.disallowed = ["Bash(git stash:*)"]
    harness = Harness(tmp_path, runner)
    with pytest.raises(PermissionDenied) as caught:
        await harness.run(make_group())
    assert caught.value.kind == "policy_forbidden"


@pytest.mark.asyncio
async def test_an_unattributable_denial_is_reported_as_unknown_not_guessed(tmp_path):
    """A confidently wrong attribution is how the original misdiagnosis happened."""
    runner = StubRunner(
        {"r1-g1-coder-g1": [coder_report("permission_denied", denied_command="make build")]}
    )
    harness = Harness(tmp_path, runner)
    with pytest.raises(PermissionDenied) as caught:
        await harness.run(make_group())
    assert caught.value.kind == "unknown"
    lines = run_log_lines(harness)
    assert any("not attributable" in line for line in lines)


@pytest.mark.asyncio
async def test_permission_denied_leaves_the_coder_session_live_for_resume(tmp_path):
    # The coder entry was recorded before the fork (plan U7); a denial must not
    # retire it, so a later plain `resume` warm-resumes the same session in the
    # same worktree instead of forking fresh.
    runner = StubRunner(
        {"r1-g1-coder-g1": [coder_report("permission_denied", denied_command="rm -rf /etc")]}
    )
    harness = Harness(tmp_path, runner)
    with pytest.raises(PermissionDenied):
        await harness.run(make_group())
    entry = harness.manifest.groups["g1"].sessions[-1]
    assert entry.role == SessionRole.CODER
    assert entry.retirement_reason is None


@pytest.mark.asyncio
async def test_permission_denied_resumes_via_plain_resume_in_existing_worktree(tmp_path):
    # Full round trip: interrupted by a denial, then a plain `resume` re-enters
    # the SAME coder session (no second fork) and the group completes normally.
    runner = StubRunner(
        {
            "r1-g1-coder-g1": [coder_report("permission_denied", denied_command="rm -rf /etc")],
            "r1-g1-reviewer-g1": [verdict("approved")],
        }
    )
    harness = Harness(tmp_path, runner)
    with pytest.raises(PermissionDenied):
        await harness.run(make_group())
    sess_id = runner.session_ids["r1-g1-coder-g1"]

    # simulates the resumed process: same manifest, same worktree, one more round
    runner.session_queues[sess_id] = [coder_report()]
    state = await harness.run(make_group())
    assert state == GroupState.COMPLETED
    assert runner.forks == ["r1-g1-coder-g1", "r1-g1-reviewer-g1"]  # no second coder fork
    lines = run_log_lines(harness)
    assert any(line.endswith(f"group g1 re-entry: resumed session {sess_id}") for line in lines)


# ------------------------------------------------------------ HITL escalation (Phase D)


def on_stuck(source: str = "workers_via_orchestrator") -> EscalationPolicy:
    return EscalationPolicy("on_stuck", source)


@pytest.mark.asyncio
async def test_needs_input_answer_resumes_the_coder_warm_and_completes(tmp_path):
    # The coder-question channel: escalate → answer → resume the SAME session with
    # the answer, no extra manifest entry, clarification uncounted by the breaker.
    runner = StubRunner(
        {
            "r1-g1-coder-g1": [
                coder_report("needs_input", question="Which cache?"),
                coder_report(),
            ],
            "r1-g1-reviewer-g1": [verdict("approved")],
        }
    )
    broker = StubBroker({EscalationKind.CODER_QUESTION: answer("use the LRU")})
    harness = Harness(tmp_path, runner, broker=broker, policy=on_stuck())
    state = await harness.run(make_group())
    assert state == GroupState.COMPLETED

    # exactly one escalation, of the question kind
    assert [req.kind for req in broker.raised] == [EscalationKind.CODER_QUESTION]
    # no extra session was recorded for the warm resume
    assert [s.name for s in harness.manifest.groups["g1"].sessions] == [
        "r1-g1-coder-g1",
        "r1-g1-reviewer-g1",
    ]
    # the coder's second prompt carried the operator's answer
    assert "use the LRU" in runner.prompts[runner.session_ids["r1-g1-coder-g1"]][1]
    # the question report persisted as a q-artifact, distinct from round artifacts
    assert (harness.store.paths.group_dir("g1") / "report-g1-q1.json").is_file()
    assert harness.rewritten == []  # a clarification never rewrites the spec


@pytest.mark.asyncio
async def test_reviewer_too_hard_skip_fails_the_group(tmp_path):
    runner = StubRunner(
        {"r1-g1-coder-g1": [coder_report()], "r1-g1-reviewer-g1": [verdict("too_hard")]}
    )
    broker = StubBroker({EscalationKind.REVIEWER_TOO_HARD: skip()})
    harness = Harness(tmp_path, runner, broker=broker, policy=on_stuck())
    with pytest.raises(GroupFailure, match="operator skipped"):
        await harness.run(make_group())
    assert [req.kind for req in broker.raised] == [EscalationKind.REVIEWER_TOO_HARD]
    assert harness.rewritten == []  # skip fails outright, no rewrite


@pytest.mark.asyncio
async def test_blocked_coder_abort_raises_run_abort_and_trips_the_broker(tmp_path):
    runner = StubRunner({"r1-g1-coder-g1": [coder_report("blocked")]})
    broker = StubBroker({EscalationKind.CODER_BLOCKED: abort()})
    harness = Harness(tmp_path, runner, broker=broker, policy=on_stuck())
    with pytest.raises(RunAbort):
        await harness.run(make_group())
    assert broker.aborted is True  # siblings' waiters were released before unwinding


@pytest.mark.asyncio
async def test_caps_exhausted_answer_grants_one_more_generation(tmp_path):
    # generation cap of 1 would fail the group; the operator's answer grants gen-2.
    runner = StubRunner(
        {
            "r1-g1-coder-g1": [coder_report()],
            "r1-g1-reviewer-g1": [verdict("changes_required", ["again"])],
            "r1-g1-coder-g2": [coder_report()],
            "r1-g1-reviewer-g2": [verdict("approved")],
        }
    )
    broker = StubBroker({EscalationKind.CAPS_EXHAUSTED: answer("try a smaller diff")})
    harness = Harness(
        tmp_path,
        runner,
        breaker=BreakerConfig(max_rounds_per_generation=1, max_generations=1),
        broker=broker,
        policy=on_stuck(),
    )
    state = await harness.run(make_group())
    assert state == GroupState.COMPLETED
    assert harness.generations == [2]
    assert [req.kind for req in broker.raised] == [EscalationKind.CAPS_EXHAUSTED]
    # the grant's guidance rode into the generation-2 handoff
    assert "try a smaller diff" in runner.prompts[runner.session_ids["r1-g1-coder-g2"]][0]


@pytest.mark.asyncio
async def test_orchestrator_only_downgrades_needs_input_to_the_rewrite_path(tmp_path):
    # With orchestrator_only, a coder question never becomes a warm resume: it is
    # escalated as coder_blocked and the answer guides a rewrite instead.
    runner = StubRunner(
        {
            "r1-g1-coder-g1": [coder_report("needs_input", question="Which cache?")],
            "r1-g1-coder-g2": [coder_report()],
            "r1-g1-reviewer-g2": [verdict("approved")],
        }
    )
    broker = StubBroker({EscalationKind.CODER_BLOCKED: answer("use the LRU")})
    harness = Harness(tmp_path, runner, broker=broker, policy=on_stuck("orchestrator_only"))
    state = await harness.run(make_group())
    assert state == GroupState.COMPLETED
    # downgraded: the question surfaced as coder_blocked, never coder_question
    assert [req.kind for req in broker.raised] == [EscalationKind.CODER_BLOCKED]
    # no warm resume happened (the first coder ran exactly one prompt)
    assert len(runner.prompts[runner.session_ids["r1-g1-coder-g1"]]) == 1
    # the operator's guidance folded into the rewrite
    assert len(harness.rewritten) == 1
    descriptions = [s.description for s in harness.rewritten[0]]
    assert any("[operator] use the LRU" in d for d in descriptions)


# ------------------------------------------------------------ lifecycle log (R10–R12)


def run_log_lines(harness: Harness) -> list[str]:
    return harness.store.paths.event_log_path.read_text().splitlines()


@pytest.mark.asyncio
async def test_autonomous_run_writes_the_full_lifecycle_log(tmp_path):
    # R10/R11: broker=None, policy=None — the same run.log lines as a HITL run:
    # worktree, round start/end, every verdict (both changes_required cycles), the
    # generation retirement and its follow-up fork, merge attempt/result, completed.
    runner = StubRunner(
        {
            "r1-g1-coder-g1": [coder_report(), coder_report()],
            "r1-g1-reviewer-g1": [
                verdict("changes_required", ["fix a"]),
                verdict("changes_required", ["fix b"]),
            ],
            "r1-g1-coder-g2": [coder_report()],
            "r1-g1-reviewer-g2": [verdict("approved")],
        }
    )
    harness = Harness(
        tmp_path, runner, breaker=BreakerConfig(max_rounds_per_generation=2, max_generations=3)
    )
    state = await harness.run(make_group())
    assert state == GroupState.COMPLETED
    assert harness.deps.broker is None and harness.deps.policy is None

    lines = run_log_lines(harness)
    expected_in_order = [
        f"group g1: worktree ready at {harness.workspace}",
        "group g1 generation 1: coder launched",
        "group g1 generation 1 round 1: started",
        "group g1 generation 1 round 1: reviewer verdict changes_required",
        "group g1 generation 1 round 1: ended (changes_required)",
        "group g1 generation 1 round 2: started",
        "group g1 generation 1 round 2: reviewer verdict changes_required",
        "group g1 generation 1 round 2: ended (changes_required)",
        "group g1 generation 1: coder retired (round threshold reached (2 rounds this generation))",
        "group g1 generation 2: coder launched",  # the follow-up fork
        "group g1 generation 2 round 1: started",
        "group g1 generation 2 round 1: reviewer verdict approved",
        "group g1 generation 2 round 1: ended (approved)",
        "group g1: merge attempt",
        "group g1: merged into the integration branch",
        "group g1: completed",
    ]
    cursor = 0
    for expected in expected_in_order:
        remaining = lines[cursor:]
        matches = [i for i, line in enumerate(remaining) if line.endswith(expected)]
        assert matches, f"missing (or out of order) lifecycle line: {expected!r}\ngot: {lines}"
        cursor += matches[0] + 1
    # R12: plain timestamped append-lines — the existing log_event format, no JSON.
    assert all(re.match(r"^\d{4}-\d{2}-\d{2}T[^ ]+  ", line) for line in lines)


@pytest.mark.asyncio
async def test_autonomous_merge_conflict_writes_the_conflict_line(tmp_path):
    runner = StubRunner(
        {
            "r1-g1-coder-g1": [coder_report(), coder_report()],
            "r1-g1-reviewer-g1": [verdict("approved")],
        }
    )
    harness = Harness(tmp_path, runner)
    harness.merge_failures.append(MergeConflict("g1 conflicts with g0", ["g0"]))
    state = await harness.run(make_group())
    assert state == GroupState.COMPLETED
    lines = run_log_lines(harness)
    assert any(line.endswith("group g1: merge conflict (g1 conflicts with g0)") for line in lines)
    # the retry after the in-place resolve still logged its attempt and result
    assert sum(line.endswith("group g1: merge attempt") for line in lines) == 2
    assert any(line.endswith("group g1: merged into the integration branch") for line in lines)


@pytest.mark.asyncio
async def test_paired_plus_extra_pass_verdict_is_logged(tmp_path):
    runner = StubRunner(
        {
            "r1-g1-coder-g1": [coder_report()],
            "r1-g1-reviewer-g1": [verdict("approved"), verdict("approved")],
        }
    )
    harness = Harness(tmp_path, runner)
    state = await harness.run(make_group(intensity=ReviewIntensity.PAIRED_PLUS))
    assert state == GroupState.COMPLETED
    lines = run_log_lines(harness)
    assert any(line.endswith("reviewer verdict approved (extra pass)") for line in lines)


@pytest.mark.asyncio
async def test_autonomous_policy_never_consults_the_broker(tmp_path):
    # Regression guard: a broker is present but the policy is autonomous, so the
    # blocked/too_hard/conflict paths run exactly as they did pre-Phase-D.
    runner = StubRunner(
        {
            "r1-g1-coder-g1": [coder_report("blocked")],
            "r1-g1-coder-g2": [coder_report()],
            "r1-g1-reviewer-g2": [verdict("approved")],
        }
    )
    broker = StubBroker({EscalationKind.CODER_BLOCKED: abort()})  # would abort if consulted
    harness = Harness(
        tmp_path,
        runner,
        broker=broker,
        policy=EscalationPolicy("autonomous", "workers_via_orchestrator"),
    )
    state = await harness.run(make_group())
    assert state == GroupState.COMPLETED  # autonomous rewrite → gen-2 → approved
    assert broker.raised == []  # the policy short-circuited before any escalation
    assert len(harness.rewritten) == 1


# ------------------------------------------------------------ re-entry (R4–R6)


def seed_reentry_session(
    harness: Harness,
    *,
    session_id: str = "sess-warm",
    generation: int = 1,
    context_tokens: int = 0,
) -> None:
    """Plant a live coder entry as if a prior process had already recorded it —
    the manifest state a plain ``resume`` finds after an INTERRUPTED restart."""
    harness.manifest.groups["g1"] = GroupManifestEntry(
        group_id="g1",
        group_name="group g1",
        summary="summary g1",
        sessions=[
            SessionEntry(
                session_id=session_id,
                role=SessionRole.CODER,
                generation=generation,
                last_context_tokens=context_tokens,
            )
        ],
    )


@pytest.mark.asyncio
async def test_reentry_warm_resumes_the_interrupted_coder(tmp_path):
    # R4: a live coder entry at the persisted generation is resumed, not forked.
    runner = StubRunner({"r1-g1-reviewer-g1": [verdict("approved")]})
    runner.prompts["sess-warm"] = []
    runner.session_queues["sess-warm"] = [coder_report()]
    harness = Harness(tmp_path, runner)
    seed_reentry_session(harness)
    state = await harness.run(make_group())
    assert state == GroupState.COMPLETED
    assert runner.forks == ["r1-g1-reviewer-g1"]  # no coder fork — resumed instead
    assert len(runner.prompts["sess-warm"]) == 1
    assert 'coder for group "group g1"' in runner.prompts["sess-warm"][0]
    lines = run_log_lines(harness)
    assert any(line.endswith("group g1 re-entry: resumed session sess-warm") for line in lines)


@pytest.mark.asyncio
async def test_reentry_resumes_round_numbering_from_completed_rounds(tmp_path):
    # Regression: a pre-crash round 1's artifacts must survive re-entry — the
    # resumed round is numbered round 2, not a second "round 1" that silently
    # overwrites them (verified live: the bug reproduced exactly this collision).
    runner = StubRunner({"r1-g1-reviewer-g1": [verdict("approved")]})
    runner.prompts["sess-warm"] = []
    runner.session_queues["sess-warm"] = [coder_report()]
    harness = Harness(tmp_path, runner)
    seed_reentry_session(harness)
    group_dir = harness.store.paths.group_dir("g1")
    group_dir.mkdir(parents=True)
    stale_report = group_dir / "report-g1-r1.json"
    stale_verdict = group_dir / "verdict-g1-r1.json"
    stale_report.write_text('{"round": "pre-crash report"}')
    stale_verdict.write_text('{"round": "pre-crash verdict"}')
    state = await harness.run(make_group())
    assert state == GroupState.COMPLETED
    assert stale_report.read_text() == '{"round": "pre-crash report"}'
    assert stale_verdict.read_text() == '{"round": "pre-crash verdict"}'
    assert (group_dir / "report-g1-r2.json").exists()
    assert (group_dir / "verdict-g1-r2.json").exists()
    lines = run_log_lines(harness)
    assert any(line.endswith("group g1 generation 1 round 2: started") for line in lines)
    assert not any("round 1: started" in line for line in lines)


@pytest.mark.asyncio
async def test_reentry_falls_through_to_fork_when_context_exceeds_the_breaker_limit(tmp_path):
    # R5: the persisted context pre-check trips before any resume is attempted.
    runner = StubRunner(
        {"r1-g1-coder-g1": [coder_report()], "r1-g1-reviewer-g1": [verdict("approved")]}
    )
    harness = Harness(tmp_path, runner, breaker=BreakerConfig(context_token_limit=100))
    seed_reentry_session(harness, context_tokens=200)
    state = await harness.run(make_group())
    assert state == GroupState.COMPLETED
    assert runner.forks == ["r1-g1-coder-g1", "r1-g1-reviewer-g1"]  # fresh fork, not a resume
    assert "sess-warm" not in runner.prompts  # never touched
    lines = run_log_lines(harness)
    reentry_lines = [line for line in lines if "re-entry" in line]
    assert len(reentry_lines) == 1
    assert reentry_lines[0].endswith(
        "group g1 re-entry: forked generation 1 (context tokens 200 exceed limit 100)"
    )


@pytest.mark.asyncio
async def test_reentry_falls_through_to_fork_when_warm_resume_raises(tmp_path):
    # R5/R6: an envelope failure on the warm attempt itself falls through to a
    # fresh fork, logging the reason instead of the resumed-session line.
    class FailOnResume(StubRunner):
        def resume(self, *, session_id, prompt, cwd, json_schema=None, on_turn=None):
            if session_id == "sess-warm":
                raise SessionError("claude exited 1")
            return super().resume(
                session_id=session_id,
                prompt=prompt,
                cwd=cwd,
                json_schema=json_schema,
                on_turn=on_turn,
            )

    runner = FailOnResume(
        {"r1-g1-coder-g1": [coder_report()], "r1-g1-reviewer-g1": [verdict("approved")]}
    )
    harness = Harness(tmp_path, runner)
    seed_reentry_session(harness)
    state = await harness.run(make_group())
    assert state == GroupState.COMPLETED
    assert runner.forks == ["r1-g1-coder-g1", "r1-g1-reviewer-g1"]
    lines = run_log_lines(harness)
    reentry_lines = [line for line in lines if "re-entry" in line]
    assert len(reentry_lines) == 1
    assert reentry_lines[0].endswith(
        "group g1 re-entry: forked generation 1 (warm resume failed: claude exited 1)"
    )


@pytest.mark.asyncio
async def test_a_usage_limit_on_reentry_does_not_spend_a_generation(tmp_path):
    """P6: the fallback fork is a second chance, and a usage limit is not one.

    Falling back is right when the *session* has become unreachable — a fresh fork
    can then succeed. Against a usage limit it fails identically, and the cost is
    not the wasted call but the generation: the breaker allows a fixed number, and
    one spent on a call that could not have succeeded is one the group no longer
    has for real work. The group stays INTERRUPTED at this generation instead, and
    a plain `resume` re-enters it once the limit resets.
    """

    class LimitOnResume(StubRunner):
        def resume(self, *, session_id, prompt, cwd, json_schema=None, on_turn=None):
            if session_id == "sess-warm":
                raise UsageLimit("claude exited 1 (--resume …): Claude AI usage limit reached")
            return super().resume(
                session_id=session_id,
                prompt=prompt,
                cwd=cwd,
                json_schema=json_schema,
                on_turn=on_turn,
            )

    runner = LimitOnResume(
        {"r1-g1-coder-g1": [coder_report()], "r1-g1-reviewer-g1": [verdict("approved")]}
    )
    harness = Harness(tmp_path, runner)
    seed_reentry_session(harness)

    with pytest.raises(UsageLimit):
        await harness.run(make_group())

    # No fork was spent, and no re-entry *outcome* was logged — nothing was
    # decided, the account was simply unavailable.
    assert runner.forks == []
    assert not any("re-entry: forked" in line for line in run_log_lines(harness))
    # Still a SessionError, so the scheduler classifies it INTERRUPTED/resumable
    # exactly as before (asserted at the scheduler level in test_scheduler.py).
    assert issubclass(UsageLimit, SessionError)


@pytest.mark.asyncio
async def test_reentry_fork_failure_propagates_instead_of_retrying(tmp_path):
    # No in-run retry loop (origin non-goal): if the fallback fork itself fails at
    # the envelope, the SessionError propagates so the scheduler lands the group
    # `interrupted` again (classification asserted by g1's scheduler tests).
    class AlwaysDown(StubRunner):
        def resume(self, *, session_id, prompt, cwd, json_schema=None, on_turn=None):
            raise SessionError("warm resume down")

        def start_fork(
            self, *, base_id, prompt, name, cwd, session_id=None, json_schema=None, on_turn=None
        ):
            raise SessionError("fork also down")

    runner = AlwaysDown({})
    harness = Harness(tmp_path, runner)
    seed_reentry_session(harness)
    with pytest.raises(SessionError, match="fork also down"):
        await harness.run(make_group())
    lines = run_log_lines(harness)
    reentry_lines = [line for line in lines if "re-entry" in line]
    assert len(reentry_lines) == 1  # exactly one re-entry line even though it fell through
    assert reentry_lines[0].endswith(
        "group g1 re-entry: forked generation 1 (warm resume failed: warm resume down)"
    )


@pytest.mark.asyncio
async def test_coder_context_tokens_persist_after_every_round(tmp_path, monkeypatch):
    # R5: the manifest reflects the latest round's usage as it happens, not only
    # once at generation end — the re-entry pre-check needs the freshest number.
    class GrowingContext(StubRunner):
        def resume(self, *, session_id, prompt, cwd, json_schema=None, on_turn=None):
            self.context_tokens[session_id] = self.context_tokens.get(session_id, 1_000) + 5_000
            return super().resume(
                session_id=session_id,
                prompt=prompt,
                cwd=cwd,
                json_schema=json_schema,
                on_turn=on_turn,
            )

    runner = GrowingContext(
        {
            "r1-g1-coder-g1": [coder_report(), coder_report()],
            "r1-g1-reviewer-g1": [
                verdict("changes_required", ["fix x"]),
                verdict("approved"),
            ],
        }
    )
    harness = Harness(tmp_path, runner)
    seen: list[int] = []
    original_save = harness.store.save

    def spying_save(manifest):
        original_save(manifest)
        coder = next(
            (s for s in manifest.groups["g1"].sessions if s.role == SessionRole.CODER), None
        )
        if coder is not None:
            seen.append(coder.last_context_tokens)

    monkeypatch.setattr(harness.store, "save", spying_save)
    state = await harness.run(make_group())
    assert state == GroupState.COMPLETED
    # round 1 persists the default (1_000); round 2 persists the bumped value —
    # proof the manifest is written every round, not just once at the end.
    assert 1_000 in seen
    assert 6_000 in seen
    assert seen.index(1_000) < seen.index(6_000)


# ------------------------------------------------------------ U7: durability


@pytest.mark.asyncio
async def test_reviewer_usage_persists_after_a_round(tmp_path):
    # Plan U7: _review_round must persist reviewer usage the way
    # _persist_coder_usage already does for the coder — otherwise the
    # reviewer's manifest entry carries a permanent zero context-token count.
    runner = StubRunner(
        {"r1-g1-coder-g1": [coder_report()], "r1-g1-reviewer-g1": [verdict("approved")]}
    )

    def seed_reviewer_tokens(name: str) -> None:
        if name == "r1-g1-reviewer-g1":
            runner.context_tokens[runner.session_ids[name]] = 42_000

    runner.on_fork = seed_reviewer_tokens
    harness = Harness(tmp_path, runner)
    state = await harness.run(make_group())
    assert state == GroupState.COMPLETED
    reviewer = next(
        s for s in harness.manifest.groups["g1"].sessions if s.role == SessionRole.REVIEWER
    )
    assert reviewer.last_context_tokens == 42_000


@pytest.mark.asyncio
async def test_first_round_crash_records_session_before_the_fork_call_completes(tmp_path):
    # Plan U7: the coder's SessionEntry is recorded *before* the blocking
    # start_fork call, not only after it returns. A crash mid-call (simulated
    # here as start_fork raising) must still leave the manifest carrying the
    # exact session id claude was invoked with, live (no retirement reason) —
    # otherwise a later resume has nothing to find and forks a brand new
    # session instead, orphaning whatever claude already did in its own
    # session before the crash.
    class CrashMidFork(StubRunner):
        def start_fork(
            self, *, base_id, prompt, name, cwd, session_id=None, json_schema=None, on_turn=None
        ):
            if name == "r1-g1-coder-g1":
                self.crashed_session_id = session_id
                raise SessionError("orchestrator crashed mid-fork")
            return super().start_fork(
                base_id=base_id,
                prompt=prompt,
                name=name,
                cwd=cwd,
                session_id=session_id,
                json_schema=json_schema,
            )

    runner = CrashMidFork({})
    harness = Harness(tmp_path, runner)
    with pytest.raises(SessionError, match="orchestrator crashed mid-fork"):
        await harness.run(make_group())

    sessions = harness.manifest.groups["g1"].sessions
    assert len(sessions) == 1
    entry = sessions[0]
    assert entry.role == SessionRole.CODER
    assert entry.retirement_reason is None
    # the manifest recorded the very id claude was actually invoked with —
    # session_id was generated by the caller and handed in, not the reverse.
    assert entry.session_id == runner.crashed_session_id

    # A later resume (fresh executor over the same manifest) finds this live
    # entry and warm-resumes it instead of forking a fresh coder session.
    resumed_runner = StubRunner({"r1-g1-reviewer-g1": [verdict("approved")]})
    resumed_runner.prompts[entry.session_id] = []
    resumed_runner.session_queues[entry.session_id] = [coder_report()]
    harness.deps.runner = resumed_runner
    state = await harness.run(make_group())
    assert state == GroupState.COMPLETED
    assert "r1-g1-coder-g1" not in resumed_runner.forks  # no fresh fork — resumed instead
    assert len(resumed_runner.prompts[entry.session_id]) == 1


class TestSurpriseBoardPersistence:
    """Plan U7: a SurpriseBoard built with ``paths`` survives a restart — a plain
    in-memory dict (``paths=None``, every other test in this file) dies with the
    process, silently dropping a surprise marked for a group that hasn't run yet."""

    def test_marked_surprise_survives_reload_from_the_run_directory(self, tmp_path):
        paths = RunPaths(tmp_path, "r1")
        board = SurpriseBoard(paths)
        surprise = Surprise(
            kind="other", description="g3 changed the API", affected_groups=["g1", "g2"]
        )
        board.mark(surprise, source_group="g3")

        reloaded = SurpriseBoard(paths)
        assert reloaded.pending_for("g1") == [surprise]
        assert reloaded.pending_for("g2") == [surprise]
        assert reloaded.pending_for("g3") == []  # the source never receives its own mark

    def test_consumed_surprise_is_never_redelivered_after_reload(self, tmp_path):
        paths = RunPaths(tmp_path, "r1")
        board = SurpriseBoard(paths)
        board.mark(Surprise(kind="other", description="x", affected_groups=["g1"]))
        board.consume("g1")

        reloaded = SurpriseBoard(paths)
        assert reloaded.pending_for("g1") == []

    def test_board_without_paths_stays_in_memory_only(self, tmp_path):
        # Every scenario elsewhere in this file constructs SurpriseBoard() bare —
        # this pins that paths=None never touches disk and behaves as before.
        board = SurpriseBoard()
        surprise = Surprise(kind="other", description="x", affected_groups=["g1"])
        board.mark(surprise)
        assert board.pending_for("g1") == [surprise]
        assert not (tmp_path / ".orchestrator").exists()


class TestRoundHeartbeat:
    """Plan P3: a running group leaves evidence of *when* it started this round,
    so an operator staring at a silent board can tell a long round from a wedged
    one. Evidence only — the loop never records a judgement about it, and the
    writer never gets a say in whether the round succeeds."""

    @pytest.mark.asyncio
    async def test_heartbeat_records_the_round_the_group_is_on(self, tmp_path):
        runner = StubRunner(
            {
                "r1-g1-coder-g1": [coder_report(), coder_report()],
                "r1-g1-reviewer-g1": [verdict("changes_required", ["fix x"]), verdict("approved")],
            }
        )
        harness = Harness(tmp_path, runner)
        assert await harness.run(make_group()) == GroupState.COMPLETED

        payload = json.loads((harness.store.paths.group_dir("g1") / "heartbeat.json").read_text())
        assert payload["group_id"] == "g1"
        assert payload["generation"] == 1
        assert payload["round"] == 2  # the second, revised round
        assert payload["round_started_at"] is not None
        assert payload["updated_at"] >= payload["round_started_at"]
        # An inference, never a stored fact: nothing here names a stall.
        assert not {"stalled", "hung", "stuck"} & set(payload)

    @pytest.mark.asyncio
    async def test_a_reentry_round_is_visible_while_the_resume_is_still_in_flight(self, tmp_path):
        """P3: the re-entry resume *is* a round, and must say so before it blocks.

        Every other heartbeat assertion here is post-hoc over the finished run,
        which is exactly why this defect survived: after the resume returns, the
        round is announced and the file looks right. The only way to see the bug
        is to read `heartbeat.json` from inside the blocking call — which is what
        a real operator does with `tail -f` while a twenty-minute re-entry writes
        files and runs tests under `round: 0, phase: resuming…`.
        """
        hb_path = RunPaths(tmp_path, "r1").group_dir("g1") / "heartbeat.json"
        in_flight: list[dict] = []

        class SnapshottingRunner(StubRunner):
            def resume(self, *, session_id, prompt, cwd, json_schema=None, on_turn=None):
                if session_id == "sess-warm" and not in_flight:
                    in_flight.append(json.loads(hb_path.read_text()))
                return super().resume(
                    session_id=session_id,
                    prompt=prompt,
                    cwd=cwd,
                    json_schema=json_schema,
                    on_turn=on_turn,
                )

        runner = SnapshottingRunner({"r1-g1-reviewer-g1": [verdict("approved")]})
        runner.prompts["sess-warm"] = []
        runner.session_queues["sess-warm"] = [coder_report()]
        harness = Harness(tmp_path, runner)
        seed_reentry_session(harness)
        # One round already on disk pre-crash, so the re-entry is round 2.
        group_dir = harness.store.paths.group_dir("g1")
        group_dir.mkdir(parents=True)
        (group_dir / "report-g1-r1.json").write_text("{}")

        assert await harness.run(make_group()) == GroupState.COMPLETED

        assert in_flight, "the resume never ran"
        payload = in_flight[0]
        assert payload["generation"] == 1
        assert payload["round"] == 2
        assert payload["round_started_at"] is not None
        # And the phase still names what the group is actually doing — mark_round
        # sets "running" internally, so this is the ordering trap in situ.
        assert payload["phase"] == "resuming the interrupted coder"

        # The round was announced once, not twice (the fallback-fork guard).
        starts = [line for line in run_log_lines(harness) if line.endswith("round 2: started")]
        assert len(starts) == 1

    @pytest.mark.asyncio
    async def test_a_broken_heartbeat_writer_never_fails_the_group(self, tmp_path, monkeypatch):
        # Break the writer from the inside, below its own guard.
        monkeypatch.setattr(
            "orchestrator.execution.heartbeat.RoundHeartbeat.snapshot",
            lambda self: (_ for _ in ()).throw(OSError("disk gone")),
        )
        runner = StubRunner({"r1-g1-coder-g1": [coder_report()]})
        harness = Harness(tmp_path, runner)
        # The write is best-effort by contract; a group merges regardless.
        assert await harness.run(make_group(intensity=ReviewIntensity.SELF_VERIFY)) == (
            GroupState.COMPLETED
        )


# ------------------------------------------------------------ U4: session bookkeeping


@pytest.mark.asyncio
async def test_started_at_and_model_are_recorded_before_the_first_round_completes(tmp_path):
    # Plan U4: _record writes started_at/model at session creation — before the
    # blocking fork call, not once its first round finishes — so an in-flight
    # group is distinguishable from one that never started.
    runner = StubRunner({"r1-g1-coder-g1": [coder_report()]})
    captured: dict = {}

    def on_fork(name: str) -> None:
        if name == "r1-g1-coder-g1":
            entry = harness.manifest.groups["g1"].sessions[0]
            captured["started_at"] = entry.started_at
            captured["model"] = entry.model

    runner.on_fork = on_fork
    harness = Harness(tmp_path, runner)
    state = await harness.run(make_group(intensity=ReviewIntensity.SELF_VERIFY))
    assert state == GroupState.COMPLETED
    assert captured["started_at"] is not None
    assert captured["model"] == "stub-model"


@pytest.mark.asyncio
async def test_inflight_context_tokens_update_while_rounds_completed_stays_zero(tmp_path):
    # Plan U4: the per-turn observer (plan U1's seam) writes last_context_tokens
    # continuously, mid-round — not only once the round finishes and
    # _persist_coder_usage runs.
    runner = StubRunner({"r1-g1-coder-g1": [coder_report()]})

    def on_fork(name: str) -> None:
        if name == "r1-g1-coder-g1":
            sid = runner.session_ids[name]
            runner.turn_sequences[sid] = [[TurnUsage(input_tokens=12_345)]]

    runner.on_fork = on_fork
    harness = Harness(tmp_path, runner)
    seen: list[tuple[int, int]] = []
    original_save = harness.store.save

    def spying_save(manifest) -> None:
        original_save(manifest)
        coder = next(
            (s for s in manifest.groups["g1"].sessions if s.role == SessionRole.CODER), None
        )
        if coder is not None:
            seen.append((coder.last_context_tokens, coder.rounds_completed))

    harness.store.save = spying_save
    state = await harness.run(make_group(intensity=ReviewIntensity.SELF_VERIFY))
    assert state == GroupState.COMPLETED
    # the save right after the mid-round turn fired: context already reflects
    # the turn, but the round it belongs to has not been counted yet.
    assert (12_345, 0) in seen


@pytest.mark.asyncio
async def test_interrupted_before_any_round_still_leaves_a_dated_manifest_entry(tmp_path):
    # Plan U4: a session that never completes a round (crash mid-fork) still
    # has a manifest entry an operator can date — started_at is set at
    # creation, not deferred to round completion.
    class CrashMidFork(StubRunner):
        def start_fork(
            self, *, base_id, prompt, name, cwd, session_id=None, json_schema=None, on_turn=None
        ):
            raise SessionError("orchestrator crashed mid-fork")

    runner = CrashMidFork({})
    harness = Harness(tmp_path, runner)
    with pytest.raises(SessionError, match="orchestrator crashed mid-fork"):
        await harness.run(make_group())
    sessions = harness.manifest.groups["g1"].sessions
    assert len(sessions) == 1
    assert sessions[0].started_at is not None
    assert sessions[0].retirement_reason is None


@pytest.mark.asyncio
async def test_resume_after_context_fallback_appends_a_second_dated_entry(tmp_path):
    # Plan U4: the observed bug — a group that died and resumed left only one
    # manifest entry, not two. The re-entry fallback path (context over the
    # breaker limit) retires the seeded entry and forks fresh, which must
    # append a second entry rather than reusing or dropping the first.
    runner = StubRunner(
        {"r1-g1-coder-g1": [coder_report()], "r1-g1-reviewer-g1": [verdict("approved")]}
    )
    harness = Harness(tmp_path, runner, breaker=BreakerConfig(context_token_limit=100))
    seed_reentry_session(harness, context_tokens=200)
    state = await harness.run(make_group())
    assert state == GroupState.COMPLETED
    sessions = [s for s in harness.manifest.groups["g1"].sessions if s.role == SessionRole.CODER]
    assert len(sessions) == 2
    assert sessions[0].retirement_reason is not None  # the seeded, unreachable entry
    assert sessions[0].started_at is None  # planted directly, not through _record
    assert sessions[1].retirement_reason is None  # the fresh fork
    assert sessions[1].started_at is not None


def test_session_entries_recorded_before_started_at_existed_load_unchanged():
    # Plan U4: a manifest written before this field existed must still load,
    # with started_at absent rather than raising.
    entry = SessionEntry.model_validate_json(
        json.dumps({"session_id": "s1", "role": "coder", "generation": 1})
    )
    assert entry.started_at is None
    assert entry.model is None


# ------------------------------------------------------------ U3: context ladder


@pytest.mark.asyncio
async def test_ladder_70_percent_fires_once_and_not_again_below_90(tmp_path):
    runner = StubRunner({"r1-g1-coder-g1": [coder_report()]})

    def on_fork(name: str) -> None:
        if name == "r1-g1-coder-g1":
            sid = runner.session_ids[name]
            runner.turn_sequences[sid] = [
                [TurnUsage(input_tokens=141_000), TurnUsage(input_tokens=150_000)]
            ]

    runner.on_fork = on_fork
    harness = Harness(tmp_path, runner, breaker=BreakerConfig(context_ladder_enabled=True))
    state = await harness.run(make_group(intensity=ReviewIntensity.SELF_VERIFY))
    assert state == GroupState.COMPLETED
    sid = runner.session_ids["r1-g1-coder-g1"]
    assert len(runner.sent[sid]) == 1
    assert "summary" in runner.sent[sid][0].lower()


@pytest.mark.asyncio
async def test_ladder_90_percent_sends_exactly_one_prioritised_conclusions_prompt(tmp_path):
    runner = StubRunner({"r1-g1-coder-g1": [coder_report()]})

    def on_fork(name: str) -> None:
        if name == "r1-g1-coder-g1":
            sid = runner.session_ids[name]
            # a single turn jumps straight past both 70% and 90%: only the
            # higher (90%) prompt is due — the 70% one was never separately due.
            runner.turn_sequences[sid] = [[TurnUsage(input_tokens=181_000)]]

    runner.on_fork = on_fork
    harness = Harness(tmp_path, runner, breaker=BreakerConfig(context_ladder_enabled=True))
    state = await harness.run(make_group(intensity=ReviewIntensity.SELF_VERIFY))
    assert state == GroupState.COMPLETED
    sid = runner.session_ids["r1-g1-coder-g1"]
    assert len(runner.sent[sid]) == 1
    assert "prioritized" in runner.sent[sid][0].lower()


@pytest.mark.asyncio
async def test_ladder_99_percent_is_not_interrupted_and_produces_a_normal_report(tmp_path):
    runner = StubRunner({"r1-g1-coder-g1": [coder_report()]})

    def on_fork(name: str) -> None:
        if name == "r1-g1-coder-g1":
            sid = runner.session_ids[name]
            runner.turn_sequences[sid] = [[TurnUsage(input_tokens=198_000)]]  # 99% of 200_000

    runner.on_fork = on_fork
    harness = Harness(tmp_path, runner, breaker=BreakerConfig(context_ladder_enabled=True))
    state = await harness.run(make_group(intensity=ReviewIntensity.SELF_VERIFY))
    assert state == GroupState.COMPLETED
    sid = runner.session_ids["r1-g1-coder-g1"]
    assert all("reached its limit" not in text.lower() for text in runner.sent[sid])


@pytest.mark.asyncio
async def test_ladder_100_percent_sends_compact_report_prompt_and_ends_gracefully(tmp_path):
    runner = StubRunner({"r1-g1-coder-g1": [coder_report()]})

    def on_fork(name: str) -> None:
        if name == "r1-g1-coder-g1":
            sid = runner.session_ids[name]
            runner.turn_sequences[sid] = [[TurnUsage(input_tokens=201_000)]]

    runner.on_fork = on_fork
    harness = Harness(tmp_path, runner, breaker=BreakerConfig(context_ladder_enabled=True))
    state = await harness.run(make_group(intensity=ReviewIntensity.SELF_VERIFY))
    # the round still ends by its own report being parsed — never killed mid-turn.
    assert state == GroupState.COMPLETED
    sid = runner.session_ids["r1-g1-coder-g1"]
    assert len(runner.sent[sid]) == 1
    assert "report" in runner.sent[sid][0].lower()


@pytest.mark.asyncio
async def test_ladder_thresholds_fire_at_most_once_per_round_even_with_many_turns(tmp_path):
    runner = StubRunner({"r1-g1-coder-g1": [coder_report()]})

    def on_fork(name: str) -> None:
        if name == "r1-g1-coder-g1":
            sid = runner.session_ids[name]
            runner.turn_sequences[sid] = [
                [
                    TurnUsage(input_tokens=145_000),
                    TurnUsage(input_tokens=150_000),
                    TurnUsage(input_tokens=182_000),
                    TurnUsage(input_tokens=190_000),
                    TurnUsage(input_tokens=205_000),
                    TurnUsage(input_tokens=210_000),
                ]
            ]

    runner.on_fork = on_fork
    harness = Harness(tmp_path, runner, breaker=BreakerConfig(context_ladder_enabled=True))
    state = await harness.run(make_group(intensity=ReviewIntensity.SELF_VERIFY))
    assert state == GroupState.COMPLETED
    sid = runner.session_ids["r1-g1-coder-g1"]
    assert len(runner.sent[sid]) == 3  # exactly one per threshold, despite six turns


@pytest.mark.asyncio
async def test_ladder_disabled_by_default_sends_nothing_even_crossing_every_threshold(tmp_path):
    runner = StubRunner({"r1-g1-coder-g1": [coder_report()]})

    def on_fork(name: str) -> None:
        if name == "r1-g1-coder-g1":
            sid = runner.session_ids[name]
            runner.turn_sequences[sid] = [[TurnUsage(input_tokens=250_000)]]

    runner.on_fork = on_fork
    harness = Harness(tmp_path, runner)  # default BreakerConfig: context_ladder_enabled=False
    state = await harness.run(make_group(intensity=ReviewIntensity.SELF_VERIFY))
    assert state == GroupState.COMPLETED
    sid = runner.session_ids["r1-g1-coder-g1"]
    assert runner.sent.get(sid, []) == []


@pytest.mark.asyncio
async def test_reentry_breaker_precheck_against_last_context_tokens_is_unchanged(tmp_path):
    # Plan U3 note: _reenter's existing breaker comparison must stay exactly as
    # it was — a session persisted above the limit is still retired on
    # re-entry, ladder or no ladder.
    runner = StubRunner(
        {"r1-g1-coder-g1": [coder_report()], "r1-g1-reviewer-g1": [verdict("approved")]}
    )
    harness = Harness(
        tmp_path,
        runner,
        breaker=BreakerConfig(context_token_limit=100, context_ladder_enabled=True),
    )
    seed_reentry_session(harness, context_tokens=200)
    state = await harness.run(make_group())
    assert state == GroupState.COMPLETED
    lines = run_log_lines(harness)
    reentry_lines = [line for line in lines if "re-entry" in line]
    assert len(reentry_lines) == 1
    assert "context tokens 200 exceed limit 100" in reentry_lines[0]


@pytest.mark.asyncio
async def test_the_launch_line_is_written_before_the_fork_not_after(tmp_path):
    """A group killed during launch must still say it was launching.

    `start_fork` blocks for as long as the base session takes to absorb the
    group's prompt — 21 minutes on a real run — and the "coder launched" line was
    written only once it returned. So an interrupted launch left a run.log whose
    last line was "worktree ready", implying the group had never started, and a
    live run showed a long silence with nothing to explain it.
    """

    class ForkNeverReturns(StubRunner):
        def start_fork(
            self, *, base_id, prompt, name, cwd, session_id=None, json_schema=None, on_turn=None
        ):
            raise SessionError("killed mid-launch")

    harness = Harness(tmp_path, ForkNeverReturns({}))
    with pytest.raises(SessionError, match="killed mid-launch"):
        await harness.run(make_group())

    lines = run_log_lines(harness)
    launching = [line for line in lines if "coder launching" in line]
    assert launching, f"no launch line survived an interrupted fork\ngot: {lines}"
    # The session id is on the line, so the transcript is findable for a group
    # that died before any round existed.
    assert re.search(r"session [0-9a-f-]{36}\)", launching[0])
    # And the completion line is absent, because the fork never returned.
    assert not any("coder launched" in line for line in lines)
